apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: 147997139858.dkr.ecr.us-east-1.amazonaws.com/customer:latest
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: NODE_ENV
              value: "prod"
            - name: MONGODB_URI
              value: "mongodb://nosql-db:27017/msytt_customer"
            - name: MSG_QUEUE_URL
              value: "amqp://guest:guest@rabbitmq-deployment:5672"
            - name: EXCHANGE_NAME
              value: "ONLINE_STORE"
            - name: APP_SECRET
              value: "a_great_secret"