apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nosql-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosql-db-deployment
  labels:
    app: nosql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nosql-db
  template:
    metadata:
      labels:
        app: nosql-db
    spec:
      containers:
        - name: nosql-db
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: nosql-db-storage
      volumes:
        - name: nosql-db-storage
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: nosql-db-pvc
