apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment 
  labels:
    app: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: 147997139858.dkr.ecr.us-east-1.amazonaws.com/products:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: NODE_ENV
              value: "prod"
            - name: MONGODB_URI
              value: "mongodb://nosql-db:27017/msytt_product"
            - name: MSG_QUEUE_URL
              value: "amqp://guest:guest@rabbitmq-deployment:5672"
            - name: EXCHANGE_NAME
              value: "ONLINE_STORE"
            - name: APP_SECRET
              value: "a_great_secret"

