apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  labels:
    app: shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: 147997139858.dkr.ecr.us-east-1.amazonaws.com/shopping:latest
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: NODE_ENV
              value: "prod"
            - name: MONGODB_URI
              value: "mongodb://nosql-db:27017/msytt_shopping"
            - name: MSG_QUEUE_URL
              value: "amqp://guest:guest@rabbitmq-deployment:5672"
            - name: EXCHANGE_NAME
              value: "ONLINE_STORE"
            - name: APP_SECRET
              value: "a_great_secret"